FROM node:16-stretch-slim AS builder

WORKDIR /app

COPY package.json package.json

RUN npm install --legacy-peer-deps --silent
COPY . /app
RUN npm run build

FROM nginx:alpine
 
COPY nginx.conf /etc/nginx/nginx.conf
RUN apk update && apk add bash
COPY --from=builder /app/build /var/www/html